"""empty message

Revision ID: 3dc93569bf1c
Revises: 
Create Date: 2024-03-10 16:53:44.193449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc93569bf1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usrname', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usrname')
    )
    op.create_table('conversation_people',
    sa.Column('conv_people_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_snd', sa.Integer(), nullable=True),
    sa.Column('user_rcv', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_rcv'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_snd'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conv_people_id')
    )
    op.create_table('uploads',
    sa.Column('upload_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('upload_data', sa.DateTime(), nullable=True),
    sa.Column('type_Up', sa.Integer(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('upload_id')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_upload_data'), ['upload_data'], unique=False)

    op.create_table('conversations',
    sa.Column('conv_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation'], ['conversation_people.conv_people_id'], ),
    sa.PrimaryKeyConstraint('conv_id')
    )
    op.create_table('mensages',
    sa.Column('mensage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conv_id', sa.Integer(), nullable=False),
    sa.Column('snd_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('time_send', sa.DateTime(), nullable=True),
    sa.Column('msg_state', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.conv_id'], ),
    sa.ForeignKeyConstraint(['snd_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('mensage_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensages')
    op.drop_table('conversations')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_upload_data'))

    op.drop_table('uploads')
    op.drop_table('conversation_people')
    op.drop_table('users')
    # ### end Alembic commands ###
